import React, { useState, useEffect } from 'react';
import { CreditCard, Printer, Download, CheckCircle2, Clock, AlertTriangle, ShieldCheck } from 'lucide-react';
import { api } from '../../services/api';
import { MaintenanceBill, LedgerEntry } from '../../types';

interface OwnerMaintenanceProps {
  propertyId: string;
  siteNumber: string;
  ownerName: string;
  totalOutstanding: number;
  onOpenPaymentModal: () => void;
}

export const OwnerMaintenance: React.FC<OwnerMaintenanceProps> = ({
  propertyId,
  siteNumber,
  ownerName,
  totalOutstanding,
  onOpenPaymentModal,
}) => {
  const [activeSubTab, setActiveSubTab] = useState<'BILLS' | 'LEDGER'>('BILLS');
  const [bills, setBills] = useState<MaintenanceBill[]>([]);
  const [ledgerEntries, setLedgerEntries] = useState<LedgerEntry[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    Promise.all([api.getOwnerBills(), api.getOwnerLedger()])
      .then(([b, l]) => {
        setBills(b || []);
        setLedgerEntries(l?.entries || []);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [propertyId]);

  const handlePrintStatement = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Top Banner & Pay CTA */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <span className="text-xs font-bold text-emerald-800 uppercase tracking-widest block mb-1">
            Site #{siteNumber} Maintenance Account
          </span>
          <div className="flex items-center gap-3">
            <span className="text-2xl sm:text-3xl font-extrabold text-slate-900 font-mono">
              ₹{totalOutstanding.toLocaleString('en-IN')}
            </span>
            <span className={`px-2.5 py-0.5 rounded text-xs font-bold ${
              totalOutstanding === 0 ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-900'
            }`}>
              {totalOutstanding === 0 ? 'Zero Dues (Cleared)' : 'Pending Balance'}
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Registered Owner: <strong className="text-slate-700">{ownerName}</strong>
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handlePrintStatement}
            className="px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer border border-slate-200"
          >
            <Printer className="w-4 h-4" />
            <span>Print Ledger</span>
          </button>

          <button
            onClick={onOpenPaymentModal}
            className="px-6 py-2.5 bg-emerald-800 hover:bg-emerald-700 text-white font-bold text-xs rounded-xl transition flex items-center gap-2 cursor-pointer shadow-md"
          >
            <CreditCard className="w-4 h-4 text-amber-300" />
            <span>{totalOutstanding > 0 ? 'Pay Maintenance Now' : 'Advance Payment'}</span>
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex bg-slate-100 p-1 rounded-xl w-fit border border-slate-200">
        <button
          onClick={() => setActiveSubTab('BILLS')}
          className={`px-4 py-2 rounded-lg text-xs font-bold transition cursor-pointer ${
            activeSubTab === 'BILLS' ? 'bg-white text-emerald-950 shadow-xs' : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          Maintenance Bills
        </button>
        <button
          onClick={() => setActiveSubTab('LEDGER')}
          className={`px-4 py-2 rounded-lg text-xs font-bold transition cursor-pointer ${
            activeSubTab === 'LEDGER' ? 'bg-white text-emerald-950 shadow-xs' : 'text-slate-600 hover:text-slate-900'
          }`}
        >
          Complete Running Ledger
        </button>
      </div>

      {/* Bills View */}
      {activeSubTab === 'BILLS' && (
        <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-xs">
          <div className="p-4 sm:p-6 border-b border-slate-100">
            <h3 className="font-bold text-base text-slate-900">Official Monthly Maintenance Bills</h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Itemized billing history generated by the Association Managing Committee.
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-slate-700">
              <thead className="bg-slate-50 text-slate-600 font-semibold border-b border-slate-200">
                <tr>
                  <th className="py-3 px-4">Bill Number</th>
                  <th className="py-3 px-4">Period</th>
                  <th className="py-3 px-4">Due Date</th>
                  <th className="py-3 px-4 text-right">Previous Bal</th>
                  <th className="py-3 px-4 text-right">Current Charge</th>
                  <th className="py-3 px-4 text-right">Late Fee</th>
                  <th className="py-3 px-4 text-right">Paid</th>
                  <th className="py-3 px-4 text-right">Outstanding</th>
                  <th className="py-3 px-4 text-center">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-mono">
                {bills.map((b) => (
                  <tr key={b.id} className="hover:bg-slate-50/80 transition font-sans">
                    <td className="py-3.5 px-4 font-mono font-bold text-slate-900">{b.bill_number}</td>
                    <td className="py-3.5 px-4 font-semibold text-slate-800">{b.billing_period}</td>
                    <td className="py-3.5 px-4 text-slate-600">{b.due_date}</td>
                    <td className="py-3.5 px-4 text-right font-mono">₹{b.previous_balance}</td>
                    <td className="py-3.5 px-4 text-right font-mono font-bold text-slate-900">₹{b.current_charge}</td>
                    <td className="py-3.5 px-4 text-right font-mono text-amber-700">₹{b.late_fee}</td>
                    <td className="py-3.5 px-4 text-right font-mono text-emerald-700">₹{b.amount_paid}</td>
                    <td className="py-3.5 px-4 text-right font-mono font-bold text-slate-900">
                      ₹{b.outstanding_amount}
                    </td>
                    <td className="py-3.5 px-4 text-center">
                      <span className={`px-2 py-0.5 rounded text-[11px] font-bold ${
                        b.status === 'Paid'
                          ? 'bg-emerald-100 text-emerald-800'
                          : b.status === 'Overdue'
                          ? 'bg-red-100 text-red-800'
                          : b.status === 'Partially Paid'
                          ? 'bg-amber-100 text-amber-800'
                          : 'bg-slate-100 text-slate-700'
                      }`}>
                        {b.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Complete Ledger View */}
      {activeSubTab === 'LEDGER' && (
        <div id="printable-statement" className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-xs p-6">
          <div className="border-b border-slate-200 pb-4 mb-5 flex items-center justify-between">
            <div>
              <h3 className="font-bold text-base text-slate-900">Financial Ledger Statement</h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Double-entry transaction audit ledger for Site #{siteNumber} · {ownerName}
              </p>
            </div>
            <div className="text-right">
              <span className="text-xs text-slate-400 block">Closing Balance</span>
              <span className="text-xl font-bold font-mono text-emerald-950">₹{totalOutstanding.toLocaleString('en-IN')}</span>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border border-slate-200">
              <thead className="bg-slate-100 text-slate-700 font-semibold border-b border-slate-200">
                <tr>
                  <th className="py-2.5 px-3">Date</th>
                  <th className="py-2.5 px-3">Description</th>
                  <th className="py-2.5 px-3 text-right">Debit (₹)</th>
                  <th className="py-2.5 px-3 text-right">Credit (₹)</th>
                  <th className="py-2.5 px-3 text-right">Running Balance (₹)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {ledgerEntries.map((e) => (
                  <tr key={e.id} className="hover:bg-slate-50/80">
                    <td className="py-2.5 px-3 text-slate-600 font-mono">{e.transaction_date}</td>
                    <td className="py-2.5 px-3 font-medium text-slate-800">{e.description}</td>
                    <td className="py-2.5 px-3 text-right font-mono font-semibold text-slate-900">
                      {e.debit > 0 ? `₹${e.debit.toLocaleString('en-IN')}` : '-'}
                    </td>
                    <td className="py-2.5 px-3 text-right font-mono font-semibold text-emerald-700">
                      {e.credit > 0 ? `₹${e.credit.toLocaleString('en-IN')}` : '-'}
                    </td>
                    <td className="py-2.5 px-3 text-right font-mono font-bold text-slate-900">
                      ₹{e.running_balance.toLocaleString('en-IN')}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};
